name: CD

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  my-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: python -m venv venv
      - uses: actions/upload-artifact@v4
        with:
          name: venv-${{ matrix.os }}
          path: venv
  release:
    runs-on: ubuntu-latest
    needs:
      - my-job
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - uses: softprops/action-gh-release@v1
        with:
          files: '*'
