name: CD

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello' > myfile.txt
      - uses: actions/upload-artifact@v4
        with:
          name: myfile.txt
          path: myfile.txt
  release:
    runs-on: ubuntu-latest
    needs:
      - myjob
    steps:
      - uses: actions/download-artifact@v4
      - run: ls
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            myfile.txt
