name: CD

on:
  push:
    tags:
      - v*.*.*

jobs:
  upload-file:
    runs-on: ubuntu-latest
    steps:
      - run: touch file.zip
      - uses: actions/upload-artifact@v4
        with:
          name: some-file
          path: file.zip
  release:
    runs-on: ubuntu-latest
    needs:
      - some-file
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: some-file
          path: file.zip
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            file.zip

