name: CD

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  my-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: echo '123' > file-${{ matrix.os }}.txt
      - uses: actions/upload-artifact@v4
        with:
          name: file-${{ matrix.os }}
          path: file-${{ matrix.os }}.txt
  release:
    runs-on: ubuntu-latest
    needs:
      - my-job
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.run_id }}
          files: '*'
