name: CD

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'File 1 content' > file1.txt
      - run: echo 'File 2 content' > file2.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: file*.txt
  release:
    runs-on: ubuntu-latest
    needs:
      - my-job
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            file1.txt
            file2.txt
